/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        black: '#000000',
        'near-black': '#17171c',
        'enterprise-green': '#003c33',
        'dark-navy': '#071829',
        'action-blue': '#1863dc',
        coral: '#ff7759',
        'soft-coral': '#ffad9b',
        'canvas-white': '#ffffff',
        'soft-stone': '#eeece7',
        'pale-green': '#edfce9',
        'pale-blue': '#f1f5ff',
        ink: '#212121',
        'muted-slate': '#93939f',
        slate: '#75758a',
        hairline: '#d9d9dd',
        'border-light': '#e5e7eb',
        'focus-blue': '#4c6ee6',
        'form-focus': '#9b60aa',
        'error-red': '#b30000',
      },
      fontFamily: {
        display: ['Space Grotesk', 'Inter', 'ui-sans-serif', 'system-ui'],
        body: ['Inter', 'Arial', 'ui-sans-serif', 'system-ui'],
        mono: ['ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      fontSize: {
        'hero': ['96px', { lineHeight: '1', letterSpacing: '-1.92px' }],
        'product-hero': ['72px', { lineHeight: '1', letterSpacing: '-1.44px' }],
        'section-display': ['60px', { lineHeight: '1', letterSpacing: '-1.2px' }],
        'section-heading': ['48px', { lineHeight: '1.2', letterSpacing: '-0.48px' }],
        'card-heading': ['32px', { lineHeight: '1.2', letterSpacing: '-0.32px' }],
        'feature-heading': ['24px', { lineHeight: '1.3' }],
        'body-lg': ['18px', { lineHeight: '1.4' }],
        'body': ['16px', { lineHeight: '1.5' }],
        'btn': ['14px', { lineHeight: '1.71' }],
        'caption': ['14px', { lineHeight: '1.4' }],
        'micro': ['12px', { lineHeight: '1.4' }],
      },
      borderRadius: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '22px',
        'xl': '30px',
        'pill': '32px',
      },
      spacing: {
        '2': '2px',
        '6': '6px',
        '10': '10px',
        '22': '22px',
        '28': '28px',
        '36': '36px',
        '56': '56px',
        '60': '60px',
        '80': '80px',
      },
    },
  },
  plugins: [],
};